#ifndef AURORA_VERSION_H
#define AURORA_VERSION_H

#define AURORA_VERSION_MAJOR 0u
#define AURORA_VERSION_MINOR 0u
#define AURORA_VERSION_PATCH 2u
#define AURORA_VERSION_FIX 4u
#define AURORA_VERSION_TEXT "0.0.2.4"
#define AURORA_VERSION_FULL "AuroraOS " AURORA_VERSION_TEXT

#define AURORA_KERNEL_BANNER AURORA_VERSION_FULL " booting"
#define AURORA_UNAME_TEXT "AuroraOS amd64 vmware " AURORA_VERSION_TEXT
#define AURORA_CLI_BANNER "AuroraOS CLI " AURORA_VERSION_TEXT
#define AURORA_KTEST_TITLE "AuroraOS 0.0.2.4 stage20.4 terminal/runtime self-test"
#define AURORA_SYSCALL_ABI_VERSION 0x00000204ull

#endif
