#[no_mangle]
pub extern "C" fn rabbitbone_rust_syscall_dispatch(no: u64, args: SysArgs) -> SyscallResult {
    let decoded = match SyscallNo::decode(no) {
        Ok(v) => v,
        Err(_) => return SyscallResult::err(VFS_ERR_UNSUPPORTED),
    };
    if let Err(e) = validate_args(decoded, args) {
        return SyscallResult::err(e);
    }
    unsafe {
        match decoded {
            SyscallNo::Version => rabbitbone_sys_version(),
            SyscallNo::WriteConsole => rabbitbone_sys_write_console(args.a0, args.a1),
            SyscallNo::Open => rabbitbone_sys_open(args.a0, args.a1),
            SyscallNo::Close => rabbitbone_sys_close(args.a0),
            SyscallNo::Read => rabbitbone_sys_read(args.a0, args.a1, args.a2),
            SyscallNo::Stat => rabbitbone_sys_stat(args.a0, args.a1),
            SyscallNo::List => rabbitbone_sys_list(args.a0, args.a1, args.a2),
            SyscallNo::Exit => rabbitbone_sys_exit(args.a0),
            SyscallNo::Log => rabbitbone_sys_log(args.a0),
            SyscallNo::Write => rabbitbone_sys_write(args.a0, args.a1, args.a2),
            SyscallNo::Seek => rabbitbone_sys_seek(args.a0, args.a1, args.a2),
            SyscallNo::Create => rabbitbone_sys_create(args.a0, args.a1, args.a2),
            SyscallNo::Mkdir => rabbitbone_sys_mkdir(args.a0),
            SyscallNo::Unlink => rabbitbone_sys_unlink(args.a0),
            SyscallNo::Ticks => rabbitbone_sys_ticks(),
            SyscallNo::GetPid => rabbitbone_sys_getpid(),
            SyscallNo::ProcInfo => rabbitbone_sys_procinfo(args.a0, args.a1),
            SyscallNo::Spawn => rabbitbone_sys_spawn(args.a0),
            SyscallNo::Wait => rabbitbone_sys_wait(args.a0, args.a1),
            SyscallNo::Yield => rabbitbone_sys_yield(),
            SyscallNo::Sleep => rabbitbone_sys_sleep(args.a0),
            SyscallNo::SchedInfo => rabbitbone_sys_schedinfo(args.a0),
            SyscallNo::Dup => rabbitbone_sys_dup(args.a0),
            SyscallNo::Tell => rabbitbone_sys_tell(args.a0),
            SyscallNo::Fstat => rabbitbone_sys_fstat(args.a0, args.a1),
            SyscallNo::FdInfo => rabbitbone_sys_fdinfo(args.a0, args.a1),
            SyscallNo::ReadDir => rabbitbone_sys_readdir(args.a0, args.a1, args.a2),
            SyscallNo::SpawnV => rabbitbone_sys_spawnv(args.a0, args.a1, args.a2),
            SyscallNo::PreemptInfo => rabbitbone_sys_preemptinfo(args.a0),
            SyscallNo::Fork => rabbitbone_sys_fork(),
            SyscallNo::Exec => rabbitbone_sys_exec(args.a0),
            SyscallNo::ExecV => rabbitbone_sys_execv(args.a0, args.a1, args.a2),
            SyscallNo::FdCtl => rabbitbone_sys_fdctl(args.a0, args.a1, args.a2),
            SyscallNo::ExecVe => rabbitbone_sys_execve(args.a0, args.a1, args.a2, args.a3, args.a4),
            SyscallNo::Pipe => rabbitbone_sys_pipe(args.a0),
            SyscallNo::PipeInfo => rabbitbone_sys_pipeinfo(args.a0, args.a1),
            SyscallNo::Dup2 => rabbitbone_sys_dup2(args.a0, args.a1, args.a2),
            SyscallNo::Poll => rabbitbone_sys_poll(args.a0, args.a1),
            SyscallNo::TtyGetInfo => rabbitbone_sys_tty_getinfo(args.a0),
            SyscallNo::TtySetMode => rabbitbone_sys_tty_setmode(args.a0),
            SyscallNo::TtyReadKey => rabbitbone_sys_tty_readkey(args.a0, args.a1),
            SyscallNo::Truncate => rabbitbone_sys_truncate(args.a0, args.a1),
            SyscallNo::Rename => rabbitbone_sys_rename(args.a0, args.a1),
            SyscallNo::Sync => rabbitbone_sys_sync(),
            SyscallNo::Fsync => rabbitbone_sys_fsync(args.a0),
            SyscallNo::StatVfs => rabbitbone_sys_statvfs(args.a0, args.a1),
            SyscallNo::InstallCommit => rabbitbone_sys_install_commit(args.a0, args.a1),
            SyscallNo::Preallocate => rabbitbone_sys_preallocate(args.a0, args.a1),
            SyscallNo::Ftruncate => rabbitbone_sys_ftruncate(args.a0, args.a1),
            SyscallNo::Fpreallocate => rabbitbone_sys_fpreallocate(args.a0, args.a1),
            SyscallNo::Chdir => rabbitbone_sys_chdir(args.a0),
            SyscallNo::Getcwd => rabbitbone_sys_getcwd(args.a0, args.a1),
            SyscallNo::Fdatasync => rabbitbone_sys_fdatasync(args.a0),
            SyscallNo::Symlink => rabbitbone_sys_symlink(args.a0, args.a1),
            SyscallNo::Readlink => rabbitbone_sys_readlink(args.a0, args.a1, args.a2),
            SyscallNo::Link => rabbitbone_sys_link(args.a0, args.a1),
            SyscallNo::Lstat => rabbitbone_sys_lstat(args.a0, args.a1),
            SyscallNo::Theme => rabbitbone_sys_theme(args.a0, args.a1),
            SyscallNo::Cred => rabbitbone_sys_cred(args.a0, args.a1, args.a2, args.a3),
            SyscallNo::Sudo => rabbitbone_sys_sudo(args.a0, args.a1, args.a2),
            SyscallNo::Chmod => rabbitbone_sys_chmod(args.a0, args.a1),
            SyscallNo::Chown => rabbitbone_sys_chown(args.a0, args.a1, args.a2),
            SyscallNo::Kctl => rabbitbone_sys_kctl(args.a0, args.a1, args.a2, args.a3),
            SyscallNo::TtyScroll => rabbitbone_sys_tty_scroll(args.a0),
            SyscallNo::TtySetCursor => rabbitbone_sys_tty_setcursor(args.a0, args.a1),
            SyscallNo::TtyClearLine => rabbitbone_sys_tty_clearline(),
            SyscallNo::TtyClear => rabbitbone_sys_tty_clear(),
            SyscallNo::TtyCursorVisible => rabbitbone_sys_tty_cursor_visible(args.a0),
            SyscallNo::Brk => rabbitbone_sys_brk(args.a0),
            SyscallNo::Sbrk => rabbitbone_sys_sbrk(args.a0),
            SyscallNo::Mmap => rabbitbone_sys_mmap(args.a0, args.a1, args.a2, args.a3, args.a4, args.a5),
            SyscallNo::Munmap => rabbitbone_sys_munmap(args.a0, args.a1),
            SyscallNo::Mprotect => rabbitbone_sys_mprotect(args.a0, args.a1, args.a2),
            SyscallNo::Signal => rabbitbone_sys_signal(args.a0, args.a1),
            SyscallNo::Sigaction => rabbitbone_sys_sigaction(args.a0, args.a1, args.a2),
            SyscallNo::Sigprocmask => rabbitbone_sys_sigprocmask(args.a0, args.a1, args.a2),
            SyscallNo::Sigpending => rabbitbone_sys_sigpending(args.a0),
            SyscallNo::Kill => rabbitbone_sys_kill(args.a0, args.a1),
            SyscallNo::Raise => rabbitbone_sys_raise(args.a0),
            SyscallNo::Getpgrp => rabbitbone_sys_getpgrp(),
            SyscallNo::Setpgid => rabbitbone_sys_setpgid(args.a0, args.a1),
            SyscallNo::Getpgid => rabbitbone_sys_getpgid(args.a0),
            SyscallNo::Setsid => rabbitbone_sys_setsid(),
            SyscallNo::Getsid => rabbitbone_sys_getsid(args.a0),
            SyscallNo::Tcgetpgrp => rabbitbone_sys_tcgetpgrp(),
            SyscallNo::Tcsetpgrp => rabbitbone_sys_tcsetpgrp(args.a0),
            SyscallNo::Sigreturn => rabbitbone_sys_sigreturn(args.a0),
        }
    }
}

#[no_mangle]
pub extern "C" fn rabbitbone_rust_syscall_name(no: u64) -> *const u8 {
    match SyscallNo::decode(no) {
        Ok(v) => v.name().as_ptr(),
        Err(_) => b"unknown\0".as_ptr(),
    }
}
