extern "C" {
    fn aurora_sys_version() -> SyscallResult;
    fn aurora_sys_write_console(ptr: u64, len: u64) -> SyscallResult;
    fn aurora_sys_open(path: u64, flags: u64) -> SyscallResult;
    fn aurora_sys_close(handle: u64) -> SyscallResult;
    fn aurora_sys_read(handle: u64, buf: u64, len: u64) -> SyscallResult;
    fn aurora_sys_stat(path: u64, stat_out: u64) -> SyscallResult;
    fn aurora_sys_list(path: u64, callback: u64, ctx: u64) -> SyscallResult;
    fn aurora_sys_exit(code: u64) -> SyscallResult;
    fn aurora_sys_log(msg: u64) -> SyscallResult;
    fn aurora_sys_write(handle: u64, buf: u64, len: u64) -> SyscallResult;
    fn aurora_sys_seek(handle: u64, offset: u64, whence: u64) -> SyscallResult;
    fn aurora_sys_create(path: u64, data: u64, len: u64) -> SyscallResult;
    fn aurora_sys_mkdir(path: u64) -> SyscallResult;
    fn aurora_sys_unlink(path: u64) -> SyscallResult;
    fn aurora_sys_ticks() -> SyscallResult;
    fn aurora_sys_getpid() -> SyscallResult;
    fn aurora_sys_procinfo(pid: u64, out: u64) -> SyscallResult;
    fn aurora_sys_spawn(path: u64) -> SyscallResult;
    fn aurora_sys_wait(pid: u64, out: u64) -> SyscallResult;
    fn aurora_sys_yield() -> SyscallResult;
    fn aurora_sys_sleep(ticks: u64) -> SyscallResult;
    fn aurora_sys_schedinfo(out: u64) -> SyscallResult;
    fn aurora_sys_dup(handle: u64) -> SyscallResult;
    fn aurora_sys_tell(handle: u64) -> SyscallResult;
    fn aurora_sys_fstat(handle: u64, out: u64) -> SyscallResult;
    fn aurora_sys_fdinfo(handle: u64, out: u64) -> SyscallResult;
    fn aurora_sys_readdir(handle: u64, index: u64, out: u64) -> SyscallResult;
    fn aurora_sys_spawnv(path: u64, argc: u64, argv: u64) -> SyscallResult;
    fn aurora_sys_preemptinfo(out: u64) -> SyscallResult;
    fn aurora_sys_fork() -> SyscallResult;
    fn aurora_sys_exec(path: u64) -> SyscallResult;
    fn aurora_sys_execv(path: u64, argc: u64, argv: u64) -> SyscallResult;
    fn aurora_sys_fdctl(handle: u64, op: u64, flags: u64) -> SyscallResult;
    fn aurora_sys_execve(path: u64, argc: u64, argv: u64, envc: u64, envp: u64) -> SyscallResult;
    fn aurora_sys_pipe(out: u64) -> SyscallResult;
    fn aurora_sys_pipeinfo(handle: u64, out: u64) -> SyscallResult;
    fn aurora_sys_dup2(src: u64, target: u64, flags: u64) -> SyscallResult;
    fn aurora_sys_poll(handle: u64, events: u64) -> SyscallResult;
    fn aurora_sys_tty_getinfo(out: u64) -> SyscallResult;
    fn aurora_sys_tty_setmode(mode: u64) -> SyscallResult;
    fn aurora_sys_tty_readkey(out: u64, flags: u64) -> SyscallResult;
    fn aurora_sys_truncate(path: u64, size: u64) -> SyscallResult;
    fn aurora_sys_rename(old_path: u64, new_path: u64) -> SyscallResult;
    fn aurora_sys_sync() -> SyscallResult;
    fn aurora_sys_fsync(handle: u64) -> SyscallResult;
    fn aurora_sys_statvfs(path: u64, out: u64) -> SyscallResult;
    fn aurora_sys_install_commit(staged_path: u64, final_path: u64) -> SyscallResult;
    fn aurora_sys_preallocate(path: u64, size: u64) -> SyscallResult;
    fn aurora_sys_ftruncate(handle: u64, size: u64) -> SyscallResult;
    fn aurora_sys_fpreallocate(handle: u64, size: u64) -> SyscallResult;
    fn aurora_sys_chdir(path: u64) -> SyscallResult;
    fn aurora_sys_getcwd(out: u64, size: u64) -> SyscallResult;
    fn aurora_sys_fdatasync(handle: u64) -> SyscallResult;
    fn aurora_sys_symlink(target: u64, link_path: u64) -> SyscallResult;
    fn aurora_sys_readlink(path: u64, out: u64, size: u64) -> SyscallResult;
    fn aurora_sys_link(old_path: u64, new_path: u64) -> SyscallResult;
    fn aurora_sys_lstat(path: u64, stat_out: u64) -> SyscallResult;
    fn aurora_sys_theme(op: u64, value: u64) -> SyscallResult;
    fn aurora_sys_cred(op: u64, arg0: u64, arg1: u64, value: u64) -> SyscallResult;
    fn aurora_sys_sudo(op: u64, password: u64, value: u64) -> SyscallResult;
    fn aurora_sys_chmod(path: u64, mode: u64) -> SyscallResult;
    fn aurora_sys_chown(path: u64, uid: u64, gid: u64) -> SyscallResult;
    fn aurora_sys_kctl(op: u64, out: u64, out_len: u64, arg: u64) -> SyscallResult;
    fn aurora_sys_tty_scroll(lines: u64) -> SyscallResult;
    fn aurora_sys_tty_setcursor(row: u64, col: u64) -> SyscallResult;
    fn aurora_sys_tty_clearline() -> SyscallResult;
    fn aurora_sys_tty_clear() -> SyscallResult;
    fn aurora_sys_tty_cursor_visible(visible: u64) -> SyscallResult;
    fn aurora_sys_brk(requested: u64) -> SyscallResult;
    fn aurora_sys_sbrk(increment: u64) -> SyscallResult;
    fn aurora_sys_mmap(requested: u64, length: u64, prot: u64, flags: u64) -> SyscallResult;
    fn aurora_sys_munmap(addr: u64, length: u64) -> SyscallResult;
    fn aurora_sys_mprotect(addr: u64, length: u64, prot: u64) -> SyscallResult;
}

