#ifndef RABBITBONE_VERSION_H
#define RABBITBONE_VERSION_H

#define RABBITBONE_VERSION_MAJOR 0u
#define RABBITBONE_VERSION_MINOR 0u
#define RABBITBONE_VERSION_PATCH 3u
#define RABBITBONE_VERSION_FIX 0u
#define RABBITBONE_VERSION_TEXT "0.0.3.0"
#define RABBITBONE_VERSION_FULL "Rabbitbone " RABBITBONE_VERSION_TEXT

#define RABBITBONE_KERNEL_BANNER RABBITBONE_VERSION_FULL " booting"
#define RABBITBONE_UNAME_TEXT "Rabbitbone amd64 vmware " RABBITBONE_VERSION_TEXT
#define RABBITBONE_CLI_BANNER "Rabbitbone CLI " RABBITBONE_VERSION_TEXT
#define RABBITBONE_KTEST_TITLE RABBITBONE_VERSION_FULL " self-test"
#define RABBITBONE_SYSCALL_ABI_VERSION 0x00000300ull

#endif
