#include "syscall/internal.h"

#include "syscall/lifecycle.inc"
#include "syscall/files_and_handles.inc"
#include "syscall/pipes.inc"
#include "syscall/usercopy_paths.inc"
#include "syscall/auth_syscalls.inc"
#include "syscall/kctl_syscalls.inc"
#include "syscall/io_syscalls.inc"
#include "syscall/fs_syscalls.inc"
#include "syscall/exec_process_syscalls.inc"
#include "syscall/fd_poll_syscalls.inc"
#include "syscall/terminal_log_dispatch.inc"
#include "syscall/selftest.inc"
