#ifndef RABBITBONE_SYSCALL_H
#define RABBITBONE_SYSCALL_H
#include <rabbitbone/types.h>
#include <rabbitbone/abi.h>
#if defined(__cplusplus)
extern "C" {
#endif

typedef enum rabbitbone_syscall_no {
    RABBITBONE_SYSCALL_VERSION = RABBITBONE_SYS_VERSION,
    RABBITBONE_SYSCALL_WRITE_CONSOLE = RABBITBONE_SYS_WRITE_CONSOLE,
    RABBITBONE_SYSCALL_OPEN = RABBITBONE_SYS_OPEN,
    RABBITBONE_SYSCALL_CLOSE = RABBITBONE_SYS_CLOSE,
    RABBITBONE_SYSCALL_READ = RABBITBONE_SYS_READ,
    RABBITBONE_SYSCALL_STAT = RABBITBONE_SYS_STAT,
    RABBITBONE_SYSCALL_LIST = RABBITBONE_SYS_LIST,
    RABBITBONE_SYSCALL_EXIT = RABBITBONE_SYS_EXIT,
    RABBITBONE_SYSCALL_LOG = RABBITBONE_SYS_LOG,
    RABBITBONE_SYSCALL_WRITE = RABBITBONE_SYS_WRITE,
    RABBITBONE_SYSCALL_SEEK = RABBITBONE_SYS_SEEK,
    RABBITBONE_SYSCALL_CREATE = RABBITBONE_SYS_CREATE,
    RABBITBONE_SYSCALL_MKDIR = RABBITBONE_SYS_MKDIR,
    RABBITBONE_SYSCALL_UNLINK = RABBITBONE_SYS_UNLINK,
    RABBITBONE_SYSCALL_TICKS = RABBITBONE_SYS_TICKS,
    RABBITBONE_SYSCALL_GETPID = RABBITBONE_SYS_GETPID,
    RABBITBONE_SYSCALL_PROCINFO = RABBITBONE_SYS_PROCINFO,
    RABBITBONE_SYSCALL_SPAWN = RABBITBONE_SYS_SPAWN,
    RABBITBONE_SYSCALL_WAIT = RABBITBONE_SYS_WAIT,
    RABBITBONE_SYSCALL_YIELD = RABBITBONE_SYS_YIELD,
    RABBITBONE_SYSCALL_SLEEP = RABBITBONE_SYS_SLEEP,
    RABBITBONE_SYSCALL_SCHEDINFO = RABBITBONE_SYS_SCHEDINFO,
    RABBITBONE_SYSCALL_DUP = RABBITBONE_SYS_DUP,
    RABBITBONE_SYSCALL_TELL = RABBITBONE_SYS_TELL,
    RABBITBONE_SYSCALL_FSTAT = RABBITBONE_SYS_FSTAT,
    RABBITBONE_SYSCALL_FDINFO = RABBITBONE_SYS_FDINFO,
    RABBITBONE_SYSCALL_READDIR = RABBITBONE_SYS_READDIR,
    RABBITBONE_SYSCALL_SPAWNV = RABBITBONE_SYS_SPAWNV,
    RABBITBONE_SYSCALL_PREEMPTINFO = RABBITBONE_SYS_PREEMPTINFO,
    RABBITBONE_SYSCALL_FORK = RABBITBONE_SYS_FORK,
    RABBITBONE_SYSCALL_EXEC = RABBITBONE_SYS_EXEC,
    RABBITBONE_SYSCALL_EXECV = RABBITBONE_SYS_EXECV,
    RABBITBONE_SYSCALL_FDCTL = RABBITBONE_SYS_FDCTL,
    RABBITBONE_SYSCALL_EXECVE = RABBITBONE_SYS_EXECVE,
    RABBITBONE_SYSCALL_PIPE = RABBITBONE_SYS_PIPE,
    RABBITBONE_SYSCALL_PIPEINFO = RABBITBONE_SYS_PIPEINFO,
    RABBITBONE_SYSCALL_DUP2 = RABBITBONE_SYS_DUP2,
    RABBITBONE_SYSCALL_POLL = RABBITBONE_SYS_POLL,
    RABBITBONE_SYSCALL_TTY_GETINFO = RABBITBONE_SYS_TTY_GETINFO,
    RABBITBONE_SYSCALL_TTY_SETMODE = RABBITBONE_SYS_TTY_SETMODE,
    RABBITBONE_SYSCALL_TTY_READKEY = RABBITBONE_SYS_TTY_READKEY,
    RABBITBONE_SYSCALL_TRUNCATE = RABBITBONE_SYS_TRUNCATE,
    RABBITBONE_SYSCALL_RENAME = RABBITBONE_SYS_RENAME,
    RABBITBONE_SYSCALL_SYNC = RABBITBONE_SYS_SYNC,
    RABBITBONE_SYSCALL_FSYNC = RABBITBONE_SYS_FSYNC,
    RABBITBONE_SYSCALL_STATVFS = RABBITBONE_SYS_STATVFS,
    RABBITBONE_SYSCALL_INSTALL_COMMIT = RABBITBONE_SYS_INSTALL_COMMIT,
    RABBITBONE_SYSCALL_PREALLOCATE = RABBITBONE_SYS_PREALLOCATE,
    RABBITBONE_SYSCALL_FTRUNCATE = RABBITBONE_SYS_FTRUNCATE,
    RABBITBONE_SYSCALL_FPREALLOCATE = RABBITBONE_SYS_FPREALLOCATE,
    RABBITBONE_SYSCALL_CHDIR = RABBITBONE_SYS_CHDIR,
    RABBITBONE_SYSCALL_GETCWD = RABBITBONE_SYS_GETCWD,
    RABBITBONE_SYSCALL_FDATASYNC = RABBITBONE_SYS_FDATASYNC,
    RABBITBONE_SYSCALL_SYMLINK = RABBITBONE_SYS_SYMLINK,
    RABBITBONE_SYSCALL_READLINK = RABBITBONE_SYS_READLINK,
    RABBITBONE_SYSCALL_LINK = RABBITBONE_SYS_LINK,
    RABBITBONE_SYSCALL_LSTAT = RABBITBONE_SYS_LSTAT,
    RABBITBONE_SYSCALL_THEME = RABBITBONE_SYS_THEME,
    RABBITBONE_SYSCALL_CRED = RABBITBONE_SYS_CRED,
    RABBITBONE_SYSCALL_SUDO = RABBITBONE_SYS_SUDO,
    RABBITBONE_SYSCALL_CHMOD = RABBITBONE_SYS_CHMOD,
    RABBITBONE_SYSCALL_CHOWN = RABBITBONE_SYS_CHOWN,
    RABBITBONE_SYSCALL_KCTL = RABBITBONE_SYS_KCTL,
    RABBITBONE_SYSCALL_TTY_SCROLL = RABBITBONE_SYS_TTY_SCROLL,
    RABBITBONE_SYSCALL_TTY_SETCURSOR = RABBITBONE_SYS_TTY_SETCURSOR,
    RABBITBONE_SYSCALL_TTY_CLEAR_LINE = RABBITBONE_SYS_TTY_CLEAR_LINE,
    RABBITBONE_SYSCALL_TTY_CLEAR = RABBITBONE_SYS_TTY_CLEAR,
    RABBITBONE_SYSCALL_TTY_CURSOR_VISIBLE = RABBITBONE_SYS_TTY_CURSOR_VISIBLE,
    RABBITBONE_SYSCALL_BRK = RABBITBONE_SYS_BRK,
    RABBITBONE_SYSCALL_SBRK = RABBITBONE_SYS_SBRK,
    RABBITBONE_SYSCALL_MMAP = RABBITBONE_SYS_MMAP,
    RABBITBONE_SYSCALL_MUNMAP = RABBITBONE_SYS_MUNMAP,
    RABBITBONE_SYSCALL_MPROTECT = RABBITBONE_SYS_MPROTECT,
    RABBITBONE_SYSCALL_SIGNAL = RABBITBONE_SYS_SIGNAL,
    RABBITBONE_SYSCALL_SIGACTION = RABBITBONE_SYS_SIGACTION,
    RABBITBONE_SYSCALL_SIGPROCMASK = RABBITBONE_SYS_SIGPROCMASK,
    RABBITBONE_SYSCALL_SIGPENDING = RABBITBONE_SYS_SIGPENDING,
    RABBITBONE_SYSCALL_KILL = RABBITBONE_SYS_KILL,
    RABBITBONE_SYSCALL_RAISE = RABBITBONE_SYS_RAISE,
    RABBITBONE_SYSCALL_GETPGRP = RABBITBONE_SYS_GETPGRP,
    RABBITBONE_SYSCALL_SETPGID = RABBITBONE_SYS_SETPGID,
    RABBITBONE_SYSCALL_GETPGID = RABBITBONE_SYS_GETPGID,
    RABBITBONE_SYSCALL_SETSID = RABBITBONE_SYS_SETSID,
    RABBITBONE_SYSCALL_GETSID = RABBITBONE_SYS_GETSID,
    RABBITBONE_SYSCALL_TCGETPGRP = RABBITBONE_SYS_TCGETPGRP,
    RABBITBONE_SYSCALL_TCSETPGRP = RABBITBONE_SYS_TCSETPGRP,
    RABBITBONE_SYSCALL_SIGRETURN = RABBITBONE_SYS_SIGRETURN,
    RABBITBONE_SYSCALL_MAX = RABBITBONE_SYS_MAX
} rabbitbone_syscall_no_t;

typedef struct syscall_result {
    i64 value;
    i64 error;
} syscall_result_t;

void syscall_init(void);
#define SYSCALL_USER_HANDLE_SNAPSHOT_BYTES 12288u

void syscall_reset_user_handles(void);
void syscall_prepare_user_handle_snapshot(void *dst, usize dst_size);
void syscall_save_user_handles(void *dst, usize dst_size);
bool syscall_retain_user_handle_snapshot(void *src, usize src_size);
void syscall_release_user_handle_snapshot(void *src, usize src_size);
void syscall_close_user_handles_with_flags(u32 flags);
void syscall_close_all_user_handles(void);
void syscall_forget_pid(u32 pid);
bool syscall_load_user_handles(const void *src, usize src_size);
usize syscall_user_handle_snapshot_size(void);

bool syscall_snapshot_open_vfs(void *snapshot, usize snapshot_size, u32 target_fd, const char *path, u32 flags, bool create_truncate);
bool syscall_snapshot_pipe_between(void *writer_snapshot, usize writer_size, u32 writer_fd, void *reader_snapshot, usize reader_size, u32 reader_fd);
syscall_result_t syscall_dispatch(u64 no, u64 a0, u64 a1, u64 a2, u64 a3, u64 a4, u64 a5);
const char *syscall_name(u64 no);
bool syscall_selftest(void);

#if defined(__cplusplus)
}
#endif
#endif
